const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
const routes = require('./routes');
const swaggerDocs = require('./swagger');
swaggerDocs(app);
app.use('/', routes);
if (require.main === module) app.listen(process.env.PORT, () => console.log('user-service listening', process.env.PORT));
module.exports = app;
